init:
  - git config --global core.autocrlf input
image: Visual Studio 2015
clone_script:
- cmd: >-
    git clone -q https://bitbucket.org/webducertutorials/detectors.git C:\projects\detectors

    git checkout -qf %APPVEYOR_REPO_BRANCH%
build_script:
  - cmd: build.cmd
build:
  verbosity: minimal
test: off
version: Build-{build}-{branch}
deploy:
- provider: NuGet
  api_key:
    secure: LRa8ypp0HoKFnPAuNeVS7Nb3EamiBqVsoZdUB8FEq1WoNEjvxcc+DvQ2FMGEZpOH
  skip_symbols: true
  on:
    branch: '/[master|develop]/'